fn_clean_exts:
    - 'eval.grp'
    # - 'R1'
    # - 'R2'
    # - 'trimmed_reads'
    - 'realignment_recalibrated'
    - 'snpEff.summary'
    - 'variant_sites'
    - 'target_sites'
    - 'all_sites'
    - 'samtools_stats'

