import os

from paip.pipelines.variant_calling import MarkDuplicates
from paip.task_types import SampleTask
from paip.helpers.create_cohort_task import create_cohort_task


class DepthOfCoverage(SampleTask):
    """
    Takes a BAM and creates a file of coverage per base in the panel regions.
    """
    REQUIRES = MarkDuplicates
    OUTPUT = 'depth_of_coverage'

    def run(self):
        with self.output().temporary_path() as tempfile:
            program_name = 'gatk3 DepthOfCoverage'
            program_options = {
                'input_bam': self.input()['dupmarked_bam'].path,
                'outfile': tempfile,
            }
            self.run_program(program_name, program_options)

        # A whole bunch of extra files are created using the original
        # output filename as a base. Since the basename for those
        # files will be the .temporary_path() generated by Luigi (something
        # like <outfile>-luigi-tmp-12345678), we need to rename them to
        # have the regular <outfile> as basename:
        extra_files = [
            '.sample_cumulative_coverage_counts',
            '.sample_cumulative_coverage_proportions',
            '.sample_interval_statistics',
            '.sample_interval_summary',
            '.sample_statistics',
            '.sample_summary',
        ]

        for extra_extension in extra_files:
            generated_file = tempfile + extra_extension
            intended_file = self.output().path + extra_extension
            os.rename(generated_file, intended_file)


DepthOfCoverageCohort = create_cohort_task(DepthOfCoverage)

