import luigi

from paip.task_types import SampleTask
from paip.pipeline import RealignAroundIndels, CreateRecalibrationTable


class RecalibrateAlignmentScores(SampleTask):
    """
    Expects a BAM file and a recalibration table file generated by GATK
    BaseRecalibrator. Runs a command to produce a new BAM recalibrated
    base scores.
    """
    def requires(self):
        return [RealignAroundIndels(sample=self.sample),
                CreateRecalibrationTable(sample=self.sample)]

    def run(self):
        temp_bam = self.output()[0].temporary_path
        temp_bai = self.output()[1].temporary_path

        with temp_bam() as self.temp_bam, temp_bai():
            program_options = {
                'input_bam': self.input()[0].fn,
                'recalibration_table': self.input()[1].fn,
                'output_bam': self.temp_output_path,
            }

            self.run_program('gatk PrintReads', program_options)

    def output(self):
        bam_fn = self.sample_path('realignment_recalibrated.bam')
        bai_fn = bam_fn + '.bai'
        return [luigi.LocalTarget(fn) for fn in [bam_fn, bai_fn]]

