import luigi

from paip.task_types import SampleTask
from paip.pipeline import RealignAroundIndels, CreateRecalibrationTable


class RecalibrateAlignmentScores(SampleTask):
    """
    Expects a BAM file and a recalibration table file generated by GATK
    BaseRecalibrator. Runs a command to produce a new BAM recalibrated
    base scores.
    """
    def requires(self):
        return [RealignAroundIndels(sample=self.sample),
                CreateRecalibrationTable(sample=self.sample)]

    def run(self):
        with self.output().temporary_path() as self.temp_bam:
            program_options = {
                'input_bam': self.input()[0].fn,
                'recalibration_table': self.input()[1].fn,
                'output_bam': self.temp_bam,
            }

            self.run_program('gatk PrintReads', program_options)

        self.rename_temp_bai()

    def output(self):
        fn = self.sample_path('realignment_recalibrated.bam')
        return luigi.LocalTarget(fn)

