from paip.task_types import SampleTask
from paip.variant_calling import RealignAroundIndels, CreateRecalibrationTable


class RecalibrateAlignmentScores(SampleTask):
    """
    Expects a BAM file and a recalibration table file generated by GATK
    BaseRecalibrator. Runs a command to produce a new BAM recalibrated
    base scores.
    """
    REQUIRES = [RealignAroundIndels, CreateRecalibrationTable]
    OUTPUT = 'realignment_recalibrated.bam'

    def run(self):
        with self.output().temporary_path() as self.temp_bam:
            program_name = 'gatk PrintReads'
            program_options = {
                'input_bam': self.input()[0].fn,
                'recalibration_table': self.input()[1].fn,
                'output_bam': self.temp_bam,
            }

            self.run_program(program_name, program_options)

        self.rename_temp_bai()

