from paip.task_types import CohortTask
from paip.pipelines.cnv_calling import FilterAndCenterMatrix


class XhmmPCA(CohortTask):
    """
    Takes the filtered and mean-centered read depth matrix generated by
    XHMM and runs a Principal Components Analysis on it.
    """
    REQUIRES = FilterAndCenterMatrix
    OUTPUT = ['DATA.RD_PCA.PC.txt',
              'DATA.RD_PCA.PC_LOADINGS.txt'
              'DATA.RD_PCA.PC_SD.txt']
    SUBDIR = 'xhmm_run'

    def run(self):
        program_name = 'xhmm PCA'
        program_options = {
            'filtered_centered_matrix': self.input()[0].path,
            'outfiles_basename': 'DATA.RD_PCA',
        }
        self.run_program(program_name, program_options)

